apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gy4s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gy4s
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gy4s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gy4s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gy4s
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gfsk-tenant/rhtap-demo-app/hacbs-test-project-gy4s@sha256:2dbeea7859aa01b42a30d1997c7802acff33ad1cea9ff56ac6b078e4582a4195
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
